spring:
  datasource:
    url: jdbc:mysql://localhost:3306/watiDB?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: chan33..

mybatis:
  mapper-locations: classpath:mapper/*.xml    # mapper映射文件位置
  type-aliases-package: com.example.watidemo.po    # 实体类所在的位置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #用于控制台打印sql语句